print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/tyler/Desktop/GitHUB/Fall2012Game1/Project/Assets/Test/Models/SchoolSchematic.mb"`)
{		
	file -o "/Users/tyler/Desktop/GitHUB/Fall2012Game1/Project/Assets/Test/Models/SchoolSchematic.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/tyler/Desktop/GitHUB/Fall2012Game1/Project/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/tyler/Desktop/GitHUB/Fall2012Game1/Project/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/tyler/Desktop/GitHUB/Fall2012Game1/Project/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
